version: '3'
services:
  rabbitmq: 
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
  
  api-gateway: 
    build: 
      context: ./
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - rabbitmq 
    volumes:
      - .:/usr/src/app # any change folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev api-gateway

  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq 
      - mysql
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev auth # overrides CMD from dockerfile

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - '3309:3306'
    volumes:
      - ./db/data:/var/lib/mysql