version: '3'
services:
  rabbitmq: 
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
  
  api-gateway: 
    build: 
      context: ./
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on: #  start dependency
      - rabbitmq 
      - auth
      - product
      - orther
    volumes:
      - .:/usr/src/app # any change folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev api-gateway 

  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq 
      - mysql_user
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev auth # overrides CMD from dockerfile

  product: 
    build: 
      context: ./
      dockerfile: ./apps/product/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq 
      - mysql_product
    volumes:
      - .:/usr/src/app # any change folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev product 

  orther: 
    build: 
      context: ./
      dockerfile: ./apps/orther/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq 
      - mysql_orther
    volumes:
      - .:/usr/src/app # any change folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev orther 

  mysql_user:
    image: mysql:8.0
    # restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: microservice_user
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - ./db/data:/var/lib/mysql

  mysql_product:
    image: mysql:8.0
    # restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: microservice_product
      MYSQL_USER: product
      MYSQL_PASSWORD: password
    ports:
      - '3308:3306'
    volumes:
      - ./db/product:/var/lib/mysql

  mysql_orther:
    image: mysql:8.0
    # restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: microservice_orther
      MYSQL_USER: orther
      MYSQL_PASSWORD: password
    ports:
      - '3309:3306'
    volumes:
      - ./db/orther:/var/lib/mysql
 